parameters:
#    olivier_news.example.class: Olivier\NewsBundle\Example

services:
#    olivier_news.example:
#        class: %olivier_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
