<?php

namespace LouezLe\RestApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenericDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenericDataRepository extends EntityRepository
{
}